timeout: 5

# Limine interface
interface_branding: Iridium
interface_branding_colour: 9CC7E8
interface_help_colour: 587A96
interface_help_colour_bright: C5E5FF
interface_help_hidden: no

# Graphical terminal
term_font_spacing: 1
term_background: 080D12
term_foreground: C9DCEB
term_background_bright: 17232D
term_foreground_bright: FFFFFF

# Entry
/Iridium
    protocol: limine
    path: boot():/boot/iridium