name: Build Iridium

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            xorriso \
            mtools \
            nasm \
            lld

      - name: Build
        run: make

      - name: Build disk image
        run: make image

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iridium-build
          path: build/**/*.hdd
          retention-days: 90